import { Link } from "react-router-dom";

// TEMPORARY: mock report data — replace with real LLM-generated report later
const mockReport = {
  patientLabel: "Prediction: PCOS",
  generatedAt: "August 3, 2026",
  clinicalSummary:
    "The multimodal analysis indicates findings consistent with Polycystic Ovary Syndrome (PCOS), based on combined ultrasound morphology and clinical/laboratory markers.",
  keyFindings: [
    "Elevated LH/FSH ratio, commonly associated with PCOS.",
    "BMI in the overweight range, a recognized risk factor.",
    "Fasting insulin levels suggesting possible insulin resistance.",
    "Self-reported menstrual irregularity.",
  ],
  hormonalInterpretation:
    "The hormonal panel shows a pattern often seen in PCOS cases, particularly the LH/FSH imbalance and elevated androgen-related markers. These values should be interpreted alongside ultrasound morphology.",
  suggestedEvaluation: [
    "Confirm with Rotterdam criteria (clinical + biochemical + ultrasound).",
    "Consider oral glucose tolerance test given insulin resistance markers.",
    "Repeat ultrasound if image quality was flagged as suboptimal.",
  ],
  evidenceSupport: [
    "Rotterdam Criteria for PCOS diagnosis",
    "Hyperandrogenism and LH/FSH ratio patterns in PCOS literature",
  ],
  disclaimer:
    "This report is generated by an AI-assisted clinical decision support system. It is intended to support, not replace, professional medical judgment. Final diagnosis and treatment decisions must be made by a qualified clinician.",
};

function ReportView() {
  const r = mockReport;

  const handleDownload = () => {
    // TEMPORARY: no PDF generation yet — will call backend /report/pdf endpoint later
    console.log("Download PDF requested (not yet implemented)");
    alert("PDF download will be available once the backend report service is connected.");
  };

  return (
    <div className="page-container">
      <h1 className="page-title">Clinical Report</h1>

      <div className="card" style={{ padding: "1.5rem" }}>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: "1rem",
          }}
        >
          <h3 style={{ margin: 0 }}>{r.patientLabel}</h3>
          <span style={{ fontSize: "0.85rem", color: "var(--color-text-muted)" }}>
            Generated: {r.generatedAt}
          </span>
        </div>

        <section style={{ marginBottom: "1.5rem" }}>
          <h4>Clinical Summary</h4>
          <p style={{ color: "var(--color-text-muted)" }}>{r.clinicalSummary}</p>
        </section>

        <section style={{ marginBottom: "1.5rem" }}>
          <h4>Key Findings</h4>
          <ul style={{ color: "var(--color-text-muted)", paddingLeft: "1.25rem" }}>
            {r.keyFindings.map((item, i) => (
              <li key={i} style={{ marginBottom: "0.4rem" }}>
                {item}
              </li>
            ))}
          </ul>
        </section>

        <section style={{ marginBottom: "1.5rem" }}>
          <h4>Hormonal Interpretation</h4>
          <p style={{ color: "var(--color-text-muted)" }}>{r.hormonalInterpretation}</p>
        </section>

        <section style={{ marginBottom: "1.5rem" }}>
          <h4>Suggested Further Evaluation</h4>
          <ul style={{ color: "var(--color-text-muted)", paddingLeft: "1.25rem" }}>
            {r.suggestedEvaluation.map((item, i) => (
              <li key={i} style={{ marginBottom: "0.4rem" }}>
                {item}
              </li>
            ))}
          </ul>
        </section>

        <section style={{ marginBottom: "1.5rem" }}>
          <h4>Evidence Support</h4>
          <ul style={{ color: "var(--color-text-muted)", paddingLeft: "1.25rem" }}>
            {r.evidenceSupport.map((item, i) => (
              <li key={i} style={{ marginBottom: "0.4rem" }}>
                {item}
              </li>
            ))}
          </ul>
        </section>

        <div
          style={{
            background: "var(--color-primary-light)",
            border: "1px solid var(--color-border)",
            borderRadius: "6px",
            padding: "1rem",
            fontSize: "0.85rem",
            color: "var(--color-primary-dark)",
          }}
        >
          <strong>Medical Disclaimer:</strong> {r.disclaimer}
        </div>
      </div>

      <div style={{ display: "flex", gap: "1rem", marginTop: "1.5rem" }}>
        <button className="btn-primary" onClick={handleDownload}>
          Download PDF
        </button>
        <Link to="/feedback">
          <button className="btn-secondary">Submit Feedback</button>
        </Link>
      </div>
    </div>
  );
}

export default ReportView;
